wip.

diff --git a/taskit b/taskit
--- a/taskit
+++ b/taskit
@@ -90,7 +90,7 @@ TASKIT_EXIT_CMDS=(
 taskit_cleanup () {
     local rc=${TASKIT_RC:-$?}
 
-    if [[ ${TASKIT_START_TIME:-} ]]; then
+    if [[ $TASKIT_START_TIME ]]; then
         local now; printf -v now "%(%s)T"
         taskit_log "Duration: $(date -u -d @$(( now - TASKIT_START_TIME )) +%T)"
     fi
@@ -142,6 +142,9 @@ TASKIT_LOG_LEVEL=${TASKIT_LOG_LEVELS[INFO]}
 export TASKFILE=
 export TASKFILE_DIR=
 
+# Absolute path to 'taskit'
+export TASKIT_SCRIPT=
+
 # Any lines printed by Taskit during task execution will be prefixed
 # by the value of this variable if set(in your Taskfile or as an environment
 # variable). Defaults to a 8-character random string.
@@ -153,6 +156,7 @@ TASKIT_SHOW_HELP=
 TASKIT_SHOW_TASKS=
 TASKIT_SKIP_DEPS=
 TASKIT_DRY_RUN=
+TASKIT_SERVER_MODE=
 
 # List of space separated task name patterns. Matched tasks will be skipped.
 TASKIT_TASK_EXCLUDES=
@@ -279,6 +283,9 @@ TASKIT_REMOTE_TASKS=()
     TASKIT_REMOTE_TASKS+=($TASK)
 }
 
+TASKIT_REMOTE_TASK_RUN_ID=0
+
+
 # These are task attributes set by taskit for internal use.
 #
 # @noargs_status - exit status of the no argument run of the task.
@@ -293,31 +300,26 @@ export TASKIT_LOCAL_DIR=${TASKIT_LOCAL_DIR:-"$HOME/.taskit"}
 export TASKIT_RUN_DIR=${TASKIT_RUN_DIR:-"$TASKIT_LOCAL_DIR/$BASHPID"}
 [[ $TASKIT_RUN_DIR =~ ^[/A-Za-z0-9._-]+$ ]] || taskit_die
 
-export TASKIT_REMOTE_DIR='~/.taskit'
-#NOTE: it must resolve to absolute path when evaluated.
+export TASKIT_REMOTE_DIR='.taskit'
+[[ ! $TASKIT_REMOTE_DIR =~ \" ]] || taskit_die
+# NOTE: if not absolute, then it's relative to ssh user's $HOME
 
 
 # The list of hostnames to ssh to when running remote tasks.
 HOSTS=()
 declare -Ag HOST_ATTRS=()  # ([hostname@attrbute_name]=attribute_value ...)
-if [[ ${TASKIT_SSH_OPTS:-} ]]; then
-    TASKIT_SSH_OPTS=($TASKIT_SSH_OPTS)
-else
-    TASKIT_SSH_OPTS=(
+
+TASKIT_SSH_OPTS=${TASKIT_SSH_OPTS:-
       -o RequestTTY=no
       -o PasswordAuthentication=no
       -o ControlMaster=auto
       -o ControlPersist=60s
-      -o ControlPath="$TASKIT_LOCAL_DIR"/ssh-%h-%p-%r
-    )
-fi
-if [[ ${TASKIT_SSH_CMD:-} ]]; then
-    TASKIT_SSH_CMD=($TASKIT_SSH_CMD)
-else
-    TASKIT_SSH_CMD=(ssh "${TASKIT_SSH_OPTS[@]}")
-fi
+      -o ControlPath=$TASKIT_LOCAL_DIR/ssh-%h-%p-%r
+}
+TASKIT_SSH_CMD=${TASKIT_SSH_CMD:-"ssh $TASKIT_SSH_OPTS"}
 
 # -----------------------------------------------------------------------------
+
 
 taskit_parse_bool () {
     local -n result_=${2:?required}
@@ -332,9 +334,11 @@ taskit_parse_bool () {
 # The resulting lines are meant to be eval'ed
 #
 taskit_split_argline () {
+    local timeout; timeout=$(type -fp timeout)
     local salt=$RANDOM$RANDOM$RANDOM$RANDOM
-    PATH= "$BASH" -rc '
-        set -ef; eval set -- "$1"
+    PATH= "$timeout" 1 "$BASH" -rc '
+        FUNCNEST=1; set -euf
+        eval set -- "$1"
         POSIXLY_CORRECT=1; \unset -f printf
         \printf "'$salt\ '%q\n" "$@"
     ' -- "$*" \
@@ -343,8 +347,20 @@ taskit_split_argline () {
 }
 
 
-
 taskit_init () {
+    if (( ${#TASKIT_EXIT_CMDS[*]} )); then
+        local oIFS=$IFS IFS=$'\n'
+        trap "${TASKIT_EXIT_CMDS[*]}" EXIT
+        IFS=$oIFS
+    fi
+
+    local d=$TASKIT_LOCAL_DIR
+    [[ -d "$d" ]] || mkdir -p "$d" || taskit_die
+    [[ -p "$d/sleep" ]] || mkfifo -m 0600 "$d/sleep" || taskit_die
+
+    sleep () { read -t ${1:?required}; } <> "$TASKIT_LOCAL_DIR/sleep"
+
+
     TASKS=($(
         tasks=$(declare -F | cut -d' ' -f3- | grep ^Task::) &&
         shopt -s extdebug &&
@@ -453,14 +469,14 @@ taskit_show_task_help () {
     }
 
     local C_ON=$C_CYAN indent="        "
-    echo "${C_ON:-}TASK${C_ON:+$C_OFF}"
-    echo "$indent${C_ON:-}${task#Task::}${C_ON:+$C_OFF} -- ${TASK_ATTRS[$task@desc]%.}."
+    echo "${C_ON}TASK${C_OFF}"
+    echo "$indent$C_ON${task#Task::}$C_OFF -- ${TASK_ATTRS[$task@desc]%.}."
 
     # print consecutive comment lines before the task definition as the
     # detailed task description.
     #
     echo
-    echo "${C_ON:-}DESCRIPTION${C_ON:+$C_OFF}"
+    echo "${C_ON}DESCRIPTION$C_OFF"
     awk -v lineno=${lineno_file%% *} '
             /^ *#/     { lines[i++]=$0; next }
             NR==lineno { for (i in lines) print lines[i]; exit 0 }
@@ -471,7 +487,7 @@ taskit_show_task_help () {
     local specs=${TASK_ATTRS[$task@param]:-}
     if [[ $specs ]]; then
         echo
-        echo "${C_ON:-}PARAMETERS${C_ON:+$C_OFF}"
+        echo "${C_ON}PARAMETERS$C_OFF"
     fi
     for spec in $specs; do
         param=${spec%[\!%=]}
@@ -483,7 +499,7 @@ taskit_show_task_help () {
 
         param_desc=${TASK_ATTRS[$task@param $param]:-}
         param_desc=${param_desc^}
-        echo -e "$indent${C_ON:-}$spec${C_ON:+$C_OFF} \t\t ${param_desc%.}."
+        echo -e "$indent$C_ON$spec$C_OFF \t\t ${param_desc%.}."
     done | column -ts$'\t'
 }
 
@@ -666,7 +682,7 @@ _taskit_run_task_with_args () {
     local -n args_dict=$2
 
     local pattern opts=$-; set -f
-    local patterns=(${TASKIT_TASK_EXCLUDES:-})
+    local patterns=($TASKIT_TASK_EXCLUDES)
     set +f; set -${opts//[is]}
     if (( ${#patterns[*]} )); then
         for pattern in "${patterns[@]}"; do
@@ -713,7 +729,7 @@ _taskit_run_task_with_args () {
     taskit_log DEBUG "Invoking $task with arguments: "\
                      "$(IFS=$'\n'; echo $(local -p |grep ^_ | sed 's/^_//'))"
 
-    if [[ ! ${TASKIT_DRY_RUN:-} ]]; then
+    if [[ ! $TASKIT_DRY_RUN ]]; then
         while :; do
             local cwd=${TASK_ATTRS[$task@cwd]:-}
             if [[ $cwd ]]; then
@@ -756,23 +772,76 @@ taskit_ssh_init () {
         vars=vars_$(( RANDOM + TASKIT_SID__++ )); declare -gA $vars
         HOST_ATTRS[$host@vars]=$vars
         HOST_ATTRS[$host@failed]=
+        # NOTE: set to the failed task name when the task's failure caused 
+        # the host to be considered "failed" (i.e., won't run any more tasks)
     done
 
-    (( ${#TASKIT_REMOTE_TASKS[*]} )) || return 0
+    # only need to continue if we really do have remote tasks and hosts
+    (( ${#TASKIT_REMOTE_TASKS[*]} )) && (( ${#HOSTS[*]} )) || return 0
+
+    declare -f "${TASKIT_REMOTE_TASKS[@]}" > "$TASKIT_RUN_DIR/Taskfile.$BASHPID"
+
+    local pids=() i
+    for host in ${HOSTS[*]:-}; do
+        rsync -pz -e "$TASKIT_SSH_CMD -p ${host##*:}" \
+            "$TASKIT_SCRIPT" "$TASKIT_RUN_DIR/Taskfile.$BASHPID" \
+            "${host%:*}:$TASKIT_REMOTE_DIR/" &
+        pids+=($!)
+    done
+    for ((i=0; i < ${#pids[*]}; i++)); do
+        wait ${pids[i]} || HOST_ATTRS[${HOSTS[i]}@failed]=1
+    done
+
+    for host in ${HOSTS[*]:-}; do
+        [[ ${HOST_ATTRS[$host@failed]} ]] && continue
+        taskit_ssh_connect "$host" || HOST_ATTRS[$host@failed]=1
+    done
+
+    for host in ${HOSTS[*]:-}; do
+        [[ ${HOST_ATTRS[$host@failed]} ]] && continue
+        taskit_remote_cmd $host "
+            if cd \"$TASKIT_REMOTE_DIR\"; then
+                while true; do
+                    printf -v t1 '%(%s)T'
+
+                    ./${TASKIT_SCRIPT##*/} -s -f ./Taskfile.$BASHPID
+                    rc=\$?; [[ -e EXIT ]] && { rm EXIT; exit \$rc; }
+
+                    printf -v t2 '%(%s)T'
+                    if (( t2 - t1 < 2 )) && (( ++taskit_runs > 5 )); then
+                        echo 'taskit server respawned too fast!' >&2
+                        exit 1
+                    fi
+                done
+            fi
+            exit
+        " || HOST_ATTRS[$host@failed]=1
+    done
+
+    for host in ${HOSTS[*]:-}; do
+        [[ ${HOST_ATTRS[$host@failed]} ]] && continue
+        taskit_remote_cmd $host ping || HOST_ATTRS[$host@failed]=1
+    done
 
     #FIXME
+    local waitlist=()
+    while (( ${#waitlist[*]} )); do
+        for host in ${HOSTS[*]:-}; do
+            [[ ${HOST_ATTRS[$host@failed]} ]] && continue
+            taskit_receive_host_vars $host
+        done
+    done
+
+
 }
 
-
 taskit_ssh_connect () {  # <hostname:port>
-    local host=$1
-    taskit_ssh_connected $host && return
-
+    local host=${1:?required}
     local run_dir=$TASKIT_RUN_DIR/$host
     mkdir -p "$run_dir" || taskit_die
     local attempt=$(( $(
             shopt -s nullglob
-            echo $run_dir/[0-9]* | tr ' ' '\n' | sort -nr | head -1
+            echo "$run_dir"/[0-9]* | tr ' ' '\n' | sort -nr | head -1
         ) + 1
     ))
     run_dir=$run_dir/$attempt
@@ -783,8 +852,8 @@ taskit_ssh_connect () {  # <hostname:port>
           stderr=$run_dir/stderr
     mkfifo -m 0600 "$stdin" "$stdout" || taskit_die
 
-    "${TASKIT_SSH_CMD[@]}" -p ${host##*:} -- ${host%:*} \
-        "exec -l /usr/bin/env bash" <"$stdin" >"$stdout" 2>"$stderr" &
+    $TASKIT_SSH_CMD -p ${host##*:} -- ${host%:*} \
+        "exec -l /usr/bin/env bash" <"$stdin" >"$stdout" 2>>"$stderr" &
     local ssh_pid=$! cmd_fd out_fd
 
     exec {cmd_fd}>"$stdin" {out_fd}<"$stdout" || taskit_die
@@ -796,81 +865,44 @@ taskit_ssh_connect () {  # <hostname:port>
     HOST_ATTRS[$host@err_file]=$stderr
 }
 
-timeout () { # <duration_spec> [-s sigspec] <command>
-    local timeout=${1:?required} signal; shift
-    if [[ $1 == -s ]]; then
-        signal=$2; shift 2
-    else
-        signal=TERM
-    fi
-    local opts=$-; set -m; ("$@") & local pid=$!; set +m; set -${opts//[is]}
-    (sleep $timeout && kill -s $signal -$pid >/dev/null 2>&1) &
-    wait $pid
-
+taskit_ssh_connected () {
+    local host=$1
+    local pid=${HOST_ATTRS[$host@ssh_pid]:-}
+    [[ $pid ]] && kill -n 0 $pid >/dev/null 2>&1
 }
 
-taskit_ssh_send () { # <hostname:port> [cmd1 cmd2 ...]
+taskit_remote_cmd () { # <hostname:port> <cmd>
     local host=${1:?required}; shift
-    local cmd_pipe=${HOST_ATTRS[$host@cmd_pipe]:-}
-    [[ -p $cmd_pipe ]] || { taskit_stack_trace; return; }
-    timeout 3 printf "%s\n" "$@" > "$cmd_pipe"
-}
-taskit_ssh_send_to_all_hosts () { # hosts_var failed_hosts_var [cmd1 cmd2 ...]
-    local host i=0
-    local -n hosts=${1:-required} failed=${2:-required}
-    for host in ${hosts[*]:-}; do
-        taskit_ssh_send $host "$@" || {
-            unset 'hosts[i]'
-            failed+=($host)
-        }
-        (( ++i ))
-    done
+    local timeout=0.1 signal=TERM
+
+    printf "%s\n" "$*" > "${HOST_ATTRS[$host@cmd_pipe]}" & local pid=$!
+    (sleep $timeout && kill -s $signal $pid) &
+
+    wait $pid
 }
 
-taskit_ssh_recv () { # <hostname:port> [timeout]
-    local host=${1:?required} out_pipe=${HOST_ATTRS[$host@out_pipe]:-}
-    [[ -p $out_pipe ]] || { taskit_stack_trace; return; }
-    read -t ${2:-1} -r < "$out_pipe"
-}
-taskit_ssh_recv_reply () { # <hostname:port> [timeout]
-    if taskit_ssh_recv "$@"; then
-        local prefix line
-        read -r prefix line <<<"$REPLY"
-        if [[ $prefix == "${TASKIT_LINE_PREFIX}_stline" ]]; then
-            eval "$line" || { taskit_stack_trace; return; }
-        fi
+
+taskit_receive_host_vars () {
+    local host=${1:?required}
+    local fds=${HOST_ATTRS[$host@fds]}
+    local out_fd=${fds#* }
+
+    if read -t 0 -u $out_fd; then
+        local line
+        IFS='' read -r -u $out_fd line
+        eval taskit_update_host_vars $host $(taskit_split_argline "$line")
     fi
 }
 
-
-_taskit_run_remote_task_with_args () {
-    (( ++TASKIT_TASK_RUN_ID ))
-    local task=$1 args=$2
-
-    local host rc out waiting=()
-
-    #  - only run the task on successful hosts
-    #  - handle @ignore_status
-    #
-    local vars pid
-    for host in ${HOSTS[*]:-}; do
-        if [[ ${HOST_ATTRS[$host@failed]} ]]; then
-            continue  #FIXME
-        fi
-
-        vars=${HOST_ATTRS[$host@vars]}  # name of the host vars array
-#FIXME
-#        if taskit_ssh_send $host "
-#            TASKIT_TASK_RUN_ID=$TASKIT_TASK_RUN_ID
-#            HOST_ATTRS[$host@vars]=$vars
-#            $(declare -p $vars) &&
-#            $(declare -p $args) &&
-#            _taskit_run_task_with_args $task $args
-#            taskit_stline rc=\$?
-#           " &&
-#             taskit_ssh_recv_reply $host
+taskit_update_host_vars () {
+    local host=${1:?required} var
+    local -n vars=${HOST_ATTRS[$host@vars]}
+    for var; do
+        vars[${var%%=*}]=${var#*=}
     done
 }
+
+
 
 
 taskit_ssh_disconnect () {  # <hostname:port>
@@ -878,7 +910,7 @@ taskit_ssh_disconnect () {  # <hostname:port>
 
     local cmd_pipe=${HOST_ATTRS[$host@cmd_pipe]:-}
     if [[ -p "$cmd_pipe" ]]; then
-        taskit_ssh_send $host "exit 0" || true
+        taskit_remote_cmd $host "exit 0" || true  #FIXME
     fi
 
     local fd
@@ -893,9 +925,10 @@ taskit_ssh_disconnect () {  # <hostname:port>
     fi
 
     local -n vars=${HOST_ATTRS[$host@vars]}; unset -v vars
-    unset "HOST_ATTRS[$host@failed]"
+    HOST_ATTRS[$host@failed]=
 }
 
+#FIXME: add to exit trap
 taskit_ssh_clean_up () {
     local host name file
     for host in ${HOSTS[*]:-}; do
@@ -924,13 +957,14 @@ options:
                )). Or use -vv to increase the verbosity.
   -f FILE      Use FILE as the Taskfile.
   -m HOSTS     A list of hostnames to run remote tasks on.
+  -s           Start taskit in server mode.
 "
 }
 
 taskit_parse_cli () {
     local option
     OPTIND=1
-    while getopts ':htf:Dv:dx:m:-' option "$@"; do
+    while getopts ':htf:Dv:dx:m:s-' option "$@"; do
         case $option in
             h) TASKIT_SHOW_HELP=1 ;;
             t) TASKIT_SHOW_TASKS=1 ;;
@@ -947,6 +981,7 @@ taskit_parse_cli () {
                ;;
             f) TASKFILE=$OPTARG ;;
             m) local oIFS=$IFS; IFS=$IFS,; HOSTS=($OPTARG); IFS=$oIFS ;;
+            s) TASKIT_SERVER_MODE=1 ;;
             -) break ;;
 
             :) taskit_die "Missing option argument for -$OPTARG" ;;
@@ -1073,11 +1108,6 @@ source () {
 }
 
 taskit_main () {
-    if (( ${#TASKIT_EXIT_CMDS[*]} )); then
-        local oIFS=$IFS IFS=$'\n'
-        trap "${TASKIT_EXIT_CMDS[*]}" EXIT
-        IFS=$oIFS
-    fi
     taskit_init || taskit_die
 
     if [[ $TASKIT_SHOW_HELP ]]; then
@@ -1088,36 +1118,75 @@ taskit_main () {
         taskit_show_tasks; exit 0
     fi
 
-    printf -v TASKIT_START_TIME "%(%s)T"
-
-    # if no tasks specified in the command line
-    if (( ! $# )); then
-
-        # run the default task if one's defined
-        if declare -F Task::default >/dev/null; then
-            taskit_run default
-        else
-            unset TASKIT_START_TIME
-        fi
-    else
+    # if a task is specified in the command line, or a default task is available
+    if (( $# )) || { declare -F Task::default >/dev/null && set -- default; }; then
+        taskit_ssh_init
+        printf -v TASKIT_START_TIME "%(%s)T"
         taskit_run "$@"
     fi
 }
 
-
-taskit_server_run_task () {
-:
-
+taskit_save_vars () {
+    local -n vars=${HOST_ATTRS[localhost@vars]}
+    local var name
+    for var; do
+        name=${var%%=*}
+        if [[ $name ]]; then
+            vars[$name]=${var#*=}
+        fi
+    done
 }
 
+taskit_server_response () {
+    local -n vars=${HOST_VARS[localhost@vars]}
+
+    vars[rc]=$TASKIT_RC
+    vars[stdout]=$(<"$TASKIT_REMOTE_DIR/stdout")
+    vars[stderr]=$(<"$TASKIT_REMOTE_DIR/stderr")
+
+    local name
+    for name in "${!vars[@]}"; do
+        printf "%q " "$name=${vars[$name]}"
+    done
+}
+
+taskit_server_run_task () {
+    taskit_run "$1" "${@:2}"  >"$TASKIT_REMOTE_DIR/stdout" 2>"$TASKIT_REMOTE_DIR/stderr" &
+}
+
+
+taskit_server_redirect_to_file () {
+    :
+}
+
+taskit_server_exit () {
+    local rc=$?
+    wait
+    touch "$TASKIT_REMOTE_DIR/EXIT"
+    exit ${1:-$rc}
+}
+
+taskit_server_ping () { printf "pong\n"; }
+
+
 taskit_server_main () {
-    local -A remote_funcs=(
-        [taskit_server_run_task]=1
-    )
+    TASKIT_EXIT_CMDS+=(taskit_server_response)
+    taskit_init || taskit_die
+
+    TASKIT_REMOTE_DIR=$(taskit_abspath "$TASKIT_REMOTE_DIR")
+
     set -m
+    local -A remote_funcs=(
+        [ping]=taskit_server_ping
+        [run]=taskit_server_run_task
+        [exit]=taskit_server_exit
+    )
+
     local cmd func task args 
-    while read -r func args; do
-        declare -F "$func" && [[ ${remote_funcs[$func]:-} ]] || continue  #FIXME: error
+    while read -r cmd args; do
+        func=${remote_funcs[$cmd]:-}
+        [[ $func ]] && declare -F "$func" >/dev/null || continue  #FIXME: send error
+
         eval $func $(taskit_split_argline "$args")
     done
 }
@@ -1126,11 +1195,21 @@ taskit_server_main () {
 
 
 if [[ $0 = "$BASH_SOURCE" ]]; then
+    TASKIT_SCRIPT=$(taskit_abspath "$0")
+
     taskit_parse_cli "$@"; set -- "${TASKIT__[@]}"
 
     source "$TASKFILE"; TASKIT_RC=$?
     [[ $TASKIT_RC = 0 ]] || taskit_die \
             "Failed sourcing Taskfile! $TASKFILE" $TASKIT_RC
 
-    taskit_main "$@"
+    [[ $IFS == $' \t\n' ]] || taskit_die "\
+Sorry! Taskit doesn't work with a global non-default IFS
+You can change it locally if it's restored back to the default IFS value."
+
+    if [[ $TASKIT_SERVER_MODE ]]; then
+        taskit_server_main "$@"
+    else
+        taskit_main "$@"
+    fi
 fi
